name: Hawser Agent
slug: hawser
version: "1.1.6"
description: Hawser agent for Dockhand (Edge mode)

arch:
  - amd64
  - armv7
  - armhf
  - aarch64

startup: services
boot: auto

# ðŸ”´ OBLIGATOIRE pour accÃ©der au docker.sock
protected: false

privileged: true

#devices:
#  - /var/run/docker.sock:/var/run/docker.sock

host_network: false

map:
  - docker_socket


options:
  dockhand_server_url: ""
  token: ""

schema:
  dockhand_server_url: str
  token: password
