name: Hawser Agent
slug: hawser
version: "1.1.7"
description: Hawser agent for Dockhand (Edge mode)

arch:
  - amd64
  - aarch64

startup: services
boot: auto


# üî¥ FORMAT HA 2026 (LISTE OBLIGATOIRE)
privileged:
  - SYS_ADMIN

# ‚ö†Ô∏è map docker_socket ignor√© en 2026 ‚Üí on l‚Äôenl√®ve
# map:
#   - docker_socket

host_network: false


options:
  dockhand_server_url: ""
  token: ""

schema:
  dockhand_server_url: str
  token: password
